# This is the docker compose file created by Victor, using his prebuilt image.
#
# Specialized docker-compose file for development environment using "manage.py runserver" command
# This file is used to start the development server and the database server
#
# The development server is started with the command:
# docker compose -f docker-compose.old.yml up -d
#

services:
  webapp-find-artek-dev:
    container_name: webapp-find-artek-OLD
    image: vicmrp/django1-6-11_python2-7-9_artek_2022-11-21-v0-2
    volumes:
      - ../00_static_data/find_artek_static:/mnt/shared-project-data
      - ./app-classic/find_artek:/usr/src/app/find_artek
      - ./:/usr/src/project/
    ports:
      - "8089:8089"
    stdin_open: true
    tty: true
    command: sh -c 'cd /usr/src/app/find_artek && python manage.py runserver 0.0.0.0:8089'
    networks:
      - shared_network


networks:
  shared_network:
    external: true
